### ISSUE TITLE
Reason for SQL Server 2017

### ISSUE THREAD

**Issue by mycall** [meysamhadeli/booking-modular-monolith#4]
Will anything break if I use 2022 edition of SQL Server?  Other images are also out of date.

**Comment by meysamhadeli** [comment]
> Will anything break if I use 2022 edition of SQL Server? Other images are also out of date.

No, Everything work correctly. You need only update version of SqlServer in this file to latest version: https://github.com/meysamhadeli/booking-modular-monolith/blob/main/deployments/docker-compose/infrastracture.yaml
> Feel free for create a pull request for update out of date the docker images :)

**Comment by meysamhadeli** [comment]
> Will anything break if I use 2022 edition of SQL Server? Other images are also out of date.

I updated the outdated version of images in [infrastracture.yaml](infrastracture.yaml](https://github.com/meysamhadeli/booking-modular-monolith/blob/main/deployments/docker-compose/infrastracture.yaml).
You can pull the new changes :)
